// ======================================
// lib/gameData.ts
// ======================================
export interface Hero {
  id: number;
  name: string;
  color?: string;
}

export interface Phase {
  step: number;
  side: "left" | "right";
  action: "ban" | "pick";
  count: number;
  desc: string;
}

export const heroes: Hero[] = [
  { id: 1, name: "Abigail" },
  { id: 2, name: "Adela" },
  { id: 3, name: "Adina" },
  { id: 4, name: "Adriana" },
  { id: 5, name: "Aiden" },
  { id: 6, name: "Alex" },
  { id: 7, name: "Alonso" },
  { id: 8, name: "Arda" },
  { id: 9, name: "Aya" },
  { id: 10, name: "Barbara" },
  { id: 11, name: "Bernice" },
  { id: 12, name: "Bianca" },
  { id: 13, name: "Blair" },
  { id: 14, name: "Camilo" },
  { id: 15, name: "Cathy" },
  { id: 16, name: "Celine" },
  { id: 17, name: "Charlotte" },
  { id: 18, name: "Chiara" },
  { id: 19, name: "Chloe" },
  { id: 20, name: "Coraline" },
  { id: 21, name: "Daniel" },
  { id: 22, name: "Darko" },
  { id: 23, name: "Debi & Marlene" },
  { id: 24, name: "Echion" },
  { id: 25, name: "Elena" },
  { id: 26, name: "Eleven" },
  { id: 27, name: "Emma" },
  { id: 28, name: "Estelle" },
  { id: 29, name: "Eva" },
  { id: 30, name: "Felix" },
  { id: 31, name: "Fenrir" },
  { id: 32, name: "Fiora" },
  { id: 33, name: "Garnet" },
  { id: 34, name: "Hart" },
  { id: 35, name: "Haze" },
  { id: 36, name: "Henry" },
  { id: 37, name: "Hisui" },
  { id: 38, name: "Hyejin" },
  { id: 39, name: "Hyunwoo" },
  { id: 40, name: "Irem" },
  { id: 41, name: "Isaac" },
  { id: 42, name: "Isol" },
  { id: 43, name: "István" },
  { id: 44, name: "Jackie" },
  { id: 45, name: "Jan" },
  { id: 46, name: "Jenny" },
  { id: 47, name: "Johann" },
  { id: 48, name: "Justyna" },
  { id: 49, name: "Karla" },
  { id: 50, name: "Katja" },
  { id: 51, name: "Kenneth" },
  { id: 52, name: "Laura" },
  { id: 53, name: "Leni" },
  { id: 54, name: "Lenore" },
  { id: 55, name: "Lenox" },
  { id: 56, name: "Leon" },
  { id: 57, name: "Li Dailin" },
  { id: 58, name: "Luke" },
  { id: 59, name: "Ly Anh" },
  { id: 60, name: "Magnus" },
  { id: 61, name: "Mai" },
  { id: 62, name: "Markus" },
  { id: 63, name: "Martina" },
  { id: 64, name: "Mirka" },
  { id: 65, name: "Nadine" },
  { id: 66, name: "Nathapon" },
  { id: 67, name: "NiaH" },
  { id: 68, name: "Nicky" },
  { id: 69, name: "Piolo" },
  { id: 70, name: "Priya" },
  { id: 71, name: "Rio" },
  { id: 72, name: "Rozzi" },
  { id: 73, name: "Shoichi" },
  { id: 74, name: "Silvia" },
  { id: 75, name: "Sissela" },
  { id: 76, name: "Sua" },
  { id: 77, name: "Tazia" },
  { id: 78, name: "Theodore" },
  { id: 79, name: "Tia" },
  { id: 80, name: "Tsubame" },
  { id: 81, name: "Vanya" },
  { id: 82, name: "William" },
  { id: 83, name: "Xiukai" },
  { id: 84, name: "Xuelin" },
  { id: 85, name: "Yuki" },
  { id: 86, name: "Yumin" },
  { id: 87, name: "Zahir" },
];

export const phases: Phase[] = [
  { step: 1, side: "left", action: "ban", count: 2, desc: "ฝั่งซ้ายแบน 2" },
  { step: 2, side: "right", action: "ban", count: 2, desc: "ฝั่งขวาแบน 2" },
  { step: 3, side: "left", action: "pick", count: 1, desc: "ฝั่งซ้ายเลือก 1" },
  { step: 4, side: "right", action: "pick", count: 2, desc: "ฝั่งขวาเลือก 2" },
  { step: 5, side: "left", action: "pick", count: 1, desc: "ฝั่งซ้ายเลือก 1" },
  { step: 6, side: "left", action: "ban", count: 2, desc: "ฝั่งซ้ายแบน 2" },
  { step: 7, side: "right", action: "ban", count: 2, desc: "ฝั่งขวาแบน 2" },
  { step: 8, side: "right", action: "pick", count: 1, desc: "ฝั่งขวาเลือก 1" },
  { step: 9, side: "left", action: "pick", count: 2, desc: "ฝั่งซ้ายเลือก 2" },
  { step: 10, side: "right", action: "pick", count: 1, desc: "ฝั่งขวาเลือก 1" },
];
